### ISSUE TITLE
Add contributors sections in readme

### ISSUE THREAD

**Issue by khushimarothi** [Rakesh9100/InstaStore#1]
### Prerequisites

- [X] I am a HSOC-22 Participant
- [X] I checked to make sure that this issue has not already been filed

### Description

I will Add a contributors section in the readme that will showcase all the contributors of this repo.

**Comment by Rakesh9100** [comment]
Okay, go for it.

**Comment by khushimarothi** [comment]
If you want i can add the badges too on the readme... Badges like PRs - welcome , showing visitors ,forks,pull request etc

**Comment by Rakesh9100** [comment]
> If you want i can add the badges too on the readme... Badges like PRs - welcome , showing visitors ,forks,pull request etc

Okay you can but it should be in proper designed format.
